-- MySQL schema for VoiceBot
CREATE TABLE Users (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(100) UNIQUE NOT NULL,
    PasswordHash VARCHAR(255) NOT NULL,
    Role VARCHAR(50) NOT NULL,
    Email VARCHAR(255),
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Sessions (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    SessionId VARCHAR(64) UNIQUE NOT NULL,
    UserId INT,
    Context JSON,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE Providers (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Type ENUM('TTS','STT','LLM') NOT NULL,
    ApiKey VARBINARY(255),
    Endpoint VARCHAR(255),
    Settings JSON,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE HardwareConfig (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    Module ENUM('TTS','STT','LLM') NOT NULL,
    Hardware ENUM('CPU','GPU') NOT NULL,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);

CREATE TABLE CsvRecords (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    FileName VARCHAR(255),
    Data JSON,
    UploadedBy INT,
    UploadedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UploadedBy) REFERENCES Users(Id)
);

CREATE TABLE Logs (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    UserId INT,
    Action VARCHAR(255),
    Details TEXT,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserId) REFERENCES Users(Id)
);
